### ISSUE TITLE
PointerEvents not initializing properly for SVG elements with 0.2.0+

### ISSUE THREAD

**Issue by bergie** [jquery/PEP#134]
It seems PointerEvents are badly broken in 0.2.1. When I load [noflo-ui](https://github.com/noflo/noflo-ui) with the new Polymer & platform release, none of the pointer events or gestures are working.

Now, in JavaScript console I do:

``` javascript
document.addEventListener('pointerdown', function (event) { console.log('pointerdown', event.target); });
document.addEventListener('trackstart', function (event) { console.log('trackstart', event.target); });
```

I try dragging in the graph editor, and nothing happens. No console output.

However, once I add this:

``` javascript
document.addEventListener('touchstart', function (event) { console.log('touchstart', event.target); });
```

everything starts working properly.

![screenshot 2014-03-08 at 16 10 32](https://f.cloud.github.com/assets/3346/2365640/d149e0f4-a6d3-11e3-967a-ba0b2c6e35a5.png)

**Comment by msegado** [comment]
@azakus / @scottgonzalez, would including the Safari bug workaround described at https://github.com/Polymer/polymer-gestures/issues/33 be within the scope of the pep.js project? I could probably help with a PR if so...

Possible approaches:
  1. Always add the fix on iOS Safari until https://bugs.webkit.org/show_bug.cgi?id=135628 is resolved
  2. Only add the fix when SVG elements are detected (if always having an extra touchstart on document.body is undesirable)
  3. Just wait until it's fixed in Safari and add a note to the Readme =)

**Comment by msegado** [comment]
A quick update for anyone experiencing the same issue: it looks like events are correctly dispatched when touching elements *within* the SVG, just not the SVG element itself. Adding a transparent rectangle with 100% width and height allows touches to generate events which bubble up and can then be caught on the SVG.

**Comment by patrickhlauke** [comment]
**PEP has now [entered emeritus status at the OpenJS Foundation](https://openjsf.org/blog/2021/02/10/pointer-events-polyfill-pep-enters-emeritus-status-at-the-openjs-foundation/). This repository is now archived.**
