### ISSUE TITLE
Remove UMD wrapper

### ISSUE THREAD

**Issue by scottgonzalez** [jquery/PEP#160]
As discussed in IRC, it doesn't make sense to use AMD for a polyfill.

**Comment by rjgotten** [comment]
> As discussed in IRC, it doesn't make sense to use AMD for a polyfill.

Not supporting AMD means AMD users are stuck with shim configuration, which complicates build-time optimization for those users. Especially for something that is an 'optional add-on' to a core application, being flexible in the build organisation matters.

Shim configuration isn't such a big problem when shimmed modules can be woven into a bundled build file in the correct dependency order. However, it becomes a very annoying problem when you want to perform conditional loading or when you want to partition modules over several bundles instead of dunking it all into one master bundle.

Not supporting AMD: Big mistake.

**Comment by scottgonzalez** [comment]
Yeah, I think this whole discussion stemmed from a very big misunderstanding. I had a feeling that was the case after I filed the issue, which is why I didn't remove the wrapper yet. I'm going to close this now.
