### ISSUE TITLE
Support for compatibility mapping

### ISSUE THREAD

**Issue by Steditor** [jquery/PEP#165]
As far as I can see, currently the chapter [Compatibility Mapping with Mouse Events](http://www.w3.org/TR/pointerevents/#compatibility-mapping-with-mouse-events) is not covered by the polyfill. Are there plans to do so?

For example, I still recieve `mousemove` events, even if I canceled the `pointerdown` event (and therefore `PREVENT MOUSE EVENT` should be set and no `mousemove` should be fired).

**Comment by Steditor** [comment]
This has also influence on the order of events. If I register to a `pointerdown` event in _capturing phase_ and to a `mousedown` event in _target phase_ or even _bubbling phase_, I'd expect the `pointerdown`event to be fired first, because the `mousedown` event is only the derived event that is fired after dispatching the pointer event. (According to the [Recommendation](http://www.w3.org/TR/pointerevents/#compatibility-mapping-with-mouse-events))
Currently, all mouse events will always be completely dispatched before the respective pointer events.

**Comment by dmethvin** [comment]
Do you have a use case in mind? Mixing application code that simultaneously requires pointer, touch, and mouse on the same elements seems like a recipe for late-night sorrow. It seems like the actual behavior and touch/mouse/pointer event order would vary by platform, based on the native events that fire. Trying to strictly normalize all that seems like a lot of additional complexity for a polyfill. 

Also note that it's optional, since the spec says "MAY".

**Comment by arschmitz** [comment]
I agree with @dmethvin this seems like it will add a lot of complexity. While it would be nice to follow the suggested event order i think the main goal of this polyfill is to implement the actual pointer events themselves so you don't have to listen to mouse events. I'm not sure we want to get into fixing inconsistencies in other tangentially related events as part of this.

**Comment by Steditor** [comment]
In my understanding it is optional that a user agent continues to fire mouse events.
In this interpretation, leaving out optional parts would imply suppressing of mouse events to only fire pointer events. Implementing the optional part would imply sticking to the order of fired events (which is pointer events first, mouse events later).

> "While Pointer Events are sourced from a variety of input devices, they are not defined as being generated from some other set of device-specific events. While possible and encouraged for compatibility, this spec does not require other device-specific events be supported (e.g. mouse events, touch events, etc.). A user agent could **support pointer events without supporting any other device events**. For compatibility with content written to mouse-specific events, this specification does provide an optional section describing how to generate compatibility mouse events based on pointer input from devices other than a mouse."
> http://www.w3.org/TR/pointerevents/#intro

The use case is in fact a simple compatibility issue - we would like to use pointer events for all parts, but some 3rd-party library relies on mouse events. For the moment we help ourselves by editing the 3rd party library, but compatibility would be our preferred solution.

**Comment by patrickhlauke** [comment]
It's perhaps a bit ambiguously stated in the spec, but

> The following describes an algorithm for how a user agent *may* map generic pointer input to mouse events for compatibility with this content.
http://www.w3.org/TR/pointerevents/#compatibility-mapping-with-mouse-events

I've always worked under the assumption that the "may" not only refers to "user agents may or may not fire mouse compat events altogether", but also to "if they decide to fire mouse compat events, they may choose to use this algorithm". As in, the entire outlined algo for when mouse events would be fired is also non-normative, and that it is within spec for a UA to decide to fire mouse compat events, but to NOT follow the algorithm either.

**Comment by scottgonzalez** [comment]
@Steditor You do understand that the following isn't reality for a polyfill, right?

> I'd expect the pointerdownevent to be fired first, because the mousedown event is only the derived event that is fired after dispatching the pointer event. 

In the polyfill, the pointer event is derived from the mouse event. The spec is written for browser vendors who actually have the ability to define when events are fired natively.

It's also worth mentioning that the polyfill is written for the target and bubbling phases only.

**Comment by Steditor** [comment]
@scottgonzalez Yet, a polyfill would be able to mock that behavior. (E.g. catch the mouse event on the uppermost level, copy the properties, cancel the event, dispatch a pointer event, dispatch a compatibility mouse event depending on the the `PREVENT MOUSE EVENT` flag and the event type.)
But I understand that you don't want to introduce this complexity to the polyfill - fair enough.
Is there a specific cause for not covering the capturing phase?

@patrickhlauke You're right, that's a second valid interpretation. I personally hope the ambiguity will be gone some day, as one of the main purposes of the spec is to reduce the number of possibilities... But again, my preferred solution would of course as well be to forget about compatibility events and only care about pointer events.

**Comment by scottgonzalez** [comment]
> Is there a specific cause for not covering the capturing phase?

jQuery has never supported it and it's only come up a few times over the years. Google didn't feel a need to support it when this was part of Polymer. So I don't see a need to add it now. Very few developers use the capturing phase.

**Comment by Steditor** [comment]
Ah, I see. I would have used it as a second approach (more of a dirty hack, though) to be sure to get the pointer event before the mouse event to stop the latter from firing.

**Comment by dmethvin** [comment]
@Steditor jQuery Core has used capturing events internally for fixing cross-browser event related issues, which is all the more reason to not recommend them to users. :smile: There don't seem to be a lot of end-developer use cases that require both capturing and bubbling events in the same page.

I think the biggest risk to the viability of Pointer Events is that the polyfill gets so big, complex, and slow that nobody wants to use it. Our goal here is not to guarantee full compatibility with every nook, cranny, and optional feature of the spec. We need to draw lines.

You mentioned that you had to edit the third-party library to get your code working with it. My guess is that even if the polyfill tried to solve this issue you'd be better off doing what you did. It's *much* easier for you to see the critical event relationships and deal with them at app level.

Can you characterize the types of changes you had to make?

**Comment by jacobrossi** [comment]
Since I wrote the "may" into the sentence in the spec that makes this optional, let me clarify its intent.  :-) The goal here of making it optional was to allow browsers to:
(a) Support the simpler touch event model for synthesizing mouse events from touch
(b) Support the pointer event model for synthesizing mouse events for touch
(c) Support no model for synthesizing mouse events for touch
where (c) is merely theoretical as no browser could work well with touch today without some model for firing mouse on older web pages.

It's worth calling out that Microsoft is currently considering changing our model from (b) to (a).  It turns out code that combines pointer+mouse is rare but code that combines touch+mouse is common. In the latter code, it's very common that it expects model (a), which means browsers need (a) if they support touch events (which we're adding to IE/Spartan).  

In order of engineering complexity, implementing model (a) is much easier from a polyfill standpoint than (b).  

But I think the question here is why mouse events are being swallowed by the polyfill. Can't the polyfill handle mouse events at the root during capture, synthesize the pointer events, and then yield back to the propagation of the native mouse event?

So then the polyfill isn't in the synthesizing the mouse event model but yet doesn't get in the middle of preventing he browser's native mouse events for touch.

**Comment by arschmitz** [comment]
@jacobrossi the polyfill is not swallowing the mouse events its simply not forcing them to happen after the pointer events.

**Comment by dmethvin** [comment]
In the polyfill's case there will always be something generating the mouse events already, either 1) the browser only generates Mouse, 2) Pointer-generates-Mouse or 3) Touch-generates-Mouse.

Case 3 worries me the most, because we'd need to generate Pointer from Touch but still deal with the wonky fake-Mouse events in a way that's "right" by the Pointer Event spec.

**Comment by jacobrossi** [comment]
If the polyfill is letting the mouse events through (however the host browser is firing them), then I don't quite understand the use case.  If there's a legacy component that's not pointer-aware, then why does the relative ordering of the mouse events wrt the generated pointer events affect the compatibility of that component?

**Comment by patrickhlauke** [comment]
> It's worth calling out that Microsoft is currently considering changing our model from (b) to (a)

Oh...interesting (keep me posted on that, so I can update my never-ending slidedeck :) )

**Comment by Steditor** [comment]
@jacobrossi The legacy component works great, but: If I am using mouse events as the legacy component does, I can make use of `stopPropagation` and `preventDefault` to be able to somehow "filter" which events reach the component.
By using pointer events I hoped to be able to both profit from the nicer API of pointer events whilst still keeping control over the mouse events via the discussed compatibility mapping, especially the `PREVENT MOUSE EVENT` flag. I obviously cannot do that if the mouse events are always fired and additionally are always fired before the pointer events, no matter the listener binding. Therefor this issue...

**Comment by patrickhlauke** [comment]
**PEP has now [entered emeritus status at the OpenJS Foundation](https://openjsf.org/blog/2021/02/10/pointer-events-polyfill-pep-enters-emeritus-status-at-the-openjs-foundation/). This repository is now archived.**
