### ISSUE TITLE
Timestamps are given in microseconds instead of milliseconds on Firefox

### ISSUE THREAD

**Issue by fb39ca4** [jquery/PEP#213]
Tested with Firefox 39 and PEP 0.3.0.

**Comment by dmethvin** [comment]
This is due to an 11-year-old Firefox bug: https://bugzilla.mozilla.org/show_bug.cgi?id=238041

Supposedly it is being worked on now: https://bugzilla.mozilla.org/show_bug.cgi?id=1026804

**Comment by patrickhlauke** [comment]
good times...I vaguely remember having to hack around this in my event listener tests...

**Comment by jzaefferer** [comment]
Since Firefox has higher precision, we should just limit the `timeStamp` property to 13 digits. That will be valid for another 250+ years.

**Comment by jzaefferer** [comment]
The given `timeStamp` [sic] property is generated by a call to [`document.createEvent`](https://github.com/jquery/PEP/blob/1c93f075d7fd04e3c55221a44a3fb40e2a1c2b4e/src/PointerEvent.js#L56). At least in Firefox this is write-only, so at this point we can't actually trim it.

Not sure how, but we should still try to fix this (if Firefox itself won't). The microsecond precision leads to bad results when passed to `Date`:
```js
new Date(1446302331076239)
> Date +047801-07-01T07:31:16.239Z
```

We can write it to a `timestamp` property, since that doesn't exist, but that won't match native events.

**Comment by scottgonzalez** [comment]
@mbrubeck thoughts?

**Comment by mbrubeck** [comment]
As far as I can see, fixing Gecko is the only way to fully fix this bug. It looks like the Gecko bug already affects mouse events and other native events in Firefox, and it seems there's a plan in place to fix it, so I don't see much value in adding a workaround to this polyfill.

**Comment by scottgonzalez** [comment]
Thanks @mbrubeck. I'll close this as won't fix/can't fix. At least it's consistent within the browser, and I assume if native Pointer Events land in Gecko before the timestamp issue is fixed, this behavior would still exist anyway.
