### ISSUE TITLE
Spec compliance: Element and GlobalEventHandlers extensions

### ISSUE THREAD

**Issue by msegado** [jquery/PEP#214]
Hey,

Are there any plans to polyfill the event handler attributes in sections 6 ([Extensions to the Element interface](http://www.w3.org/TR/pointerevents/#extensions-to-the-element-interface)) and 7 ([Extensions to the GlobalEventHandlers interface](http://www.w3.org/TR/pointerevents/#extensions-to-the-globaleventhandlers-interface)) of the current spec? This would allow authors to do things like `document.onpointerdown = function(event) { ... }`.

For reference:

```
partial interface Element {
                attribute EventHandler ongotpointercapture;
                attribute EventHandler onlostpointercapture;
    void setPointerCapture (long pointerId);
    void releasePointerCapture (long pointerId);
};
```

```
partial interface GlobalEventHandlers {
                attribute EventHandler onpointerdown;
                attribute EventHandler onpointermove;
                attribute EventHandler onpointerup;
                attribute EventHandler onpointercancel;
                attribute EventHandler onpointerover;
                attribute EventHandler onpointerout;
                attribute EventHandler onpointerenter;
                attribute EventHandler onpointerleave;
};
```

I expect full support might be difficult (you'd have to monitor for mutations to the attributes on everything that implements the `GlobalEventHandlers` interface to do it), but partial support may be easier to swing - e.g., the `onpointer*` and `ongot/lostpointercapture` _properties_ on `Element.prototype`, `Document.prototype`, and `Window.prototype` could be defining setters which invoke `addEventListener` and `removeEventListener` as necessary.

**Comment by msegado** [comment]
(alternatively, it could just be listed as a caveat in the Readme if the benefit-to-implementation-effort ratio is too low to be worth pursuing)

**Comment by scottgonzalez** [comment]
We've decided to implement the properties, but not the attributes.

**Comment by jzaefferer** [comment]
Can someone provide some pseudo code to outline how this would look like to implement?

**Comment by scottgonzalez** [comment]
See [`applyPolyfill()` in the capture module](https://github.com/jquery/PEP/blob/1c93f075d7fd04e3c55221a44a3fb40e2a1c2b4e/src/capture.js#L30) for defining properties on all elements (note that we'll also need to add properties to `document` (could use `Node` instead of `Element` and `window` (would need explicit handling even if extending `Node`)). For the actual event binding, just use `addEventListener()`, but we'll need to track the functions so that we can remove the associate listener if the property is changed.

**Comment by jzaefferer** [comment]
Thanks, that helps. Unfortunately it doesn't look like I'll be able to work on this anytime soon.

**Comment by miguelcobain** [comment]
Would love this feature. If someone could outline what would take to implement this, I'd be willing to do it.

**Comment by scottgonzalez** [comment]
@miguelcobain What information do you need beyond what I listed above?

**Comment by miguelcobain** [comment]
@scottgonzalez Basically something a bit more noobie proof. 😄 

From your comment above I think I understand how to define properties on `Node`/`Element`.
However, what properties should I define?
What would be their value?
How/where would I use `addEventListener` from there?

**Comment by miguelcobain** [comment]
@scottgonzalez so, my guess is:
- define all the `onpointer*` properties
- call `addEventListener` on all elements with `touch-action` attribute
- if a `onpointer*` property is present, call it on the handler

**Comment by scottgonzalez** [comment]
You should be able to use `Object.defineProperty()` to define the `onpointer*` methods and just pass the callback to `addEventListener()` on the same node. I don't think you'll need to worry about `touch-action`, since you're just forwarding the callback from the property to `addEventListener()` and then all of the normal PEP code will take over from there. You will need to do a little bookkeeping to track the fact that the property has been set so that if it gets set again, you know to remove the existing event listener. You'll also need to detect if it gets set to `null`/`undefined` which would also require removing the existing event listener (if one exists).

**Comment by patrickhlauke** [comment]
**PEP has now [entered emeritus status at the OpenJS Foundation](https://openjsf.org/blog/2021/02/10/pointer-events-polyfill-pep-enters-emeritus-status-at-the-openjs-foundation/). This repository is now archived.**
