### ISSUE TITLE
Suggestion for documentation - PEP with React

### ISSUE THREAD

**Issue by ghost** [jquery/PEP#255]
In order to get the PEP polyfill working with standard elements in React JSX one must add the 'touch-action' attribute [after the component has mounted](http://stackoverflow.com/a/31273478) as [non-standard attributes will not be rendered](https://facebook.github.io/react/docs/jsx-gotchas.html#custom-html-attributes).

eg. this will not render the 'touch-action' attribute:

``` js
  render() {
    <div touch-action="none">does not emit events</div>
  }
```

Whereas this works fine:

``` js
  componentDidMount() {
    this.refs.test.setAttribute('touch-action', 'none');
  }
```

``` js
  render() {
    <div ref="test">emits events</div>
  }
```

This may be too specific specific to include in the documentation, but I thought it might be helpful for those who have run into the same problem.

**Comment by jzaefferer** [comment]
Once #151 is implemented we no longer need the non-standard attribute. So hopefully this issue is obsolete soon.

**Comment by scottgonzalez** [comment]
We decided that this can be added to the README, in a section similar to [Using PEP with jQuery](https://github.com/jquery/PEP/tree/master#using-pep-with-jquery). Can you send a PR adding that?

**Comment by MilllerTime** [comment]
I wrote a React component that allows declarative pointer event binding, and setting of the `touch-action` attribute for PEP. No need to manage anything in lifecycle hooks across multiple components 🙂

[`<Pointable />` component gist (see comment for usage)](https://gist.github.com/MilllerTime/53d67483cc908bdccbcd2a88dbf21838)

It has been working for me as an easy substitute until React officially supports pointer events. Even then, it may be handy for the `touch-action` attribute if Safari keeps holding out on pointer events.

I've been wanting to put this on npm but haven't found time to setup a dedicated build for it and extract the tests out of my current project. It's a single dependency free component, so should be easy to drop into your project if you need pointer events with React.

This doesn't resolve the documentation issue, but hopefully is helpful.

**Comment by scottgonzalez** [comment]
I'm going to close this. If someone wants to send a PR with documentation, we can certainly add it.

**Comment by MilllerTime** [comment]
Hey @scottgonzalez, I'm afraid any explanation to do this the _right way_ gets pretty lengthy if all bases are to be covered. While it's easy to make a React component that binds pointer events and sets `touch-action` based on _initial_ props, the beauty of React is how it can reconcile changes to a component over its lifetime. However since pointer events and `touch-action` aren't supported by React, it won't do this reconciliation. In order to build a component that responds gracefully to changes in pointer event binding and `touch-action` (like React normally does with other props), one must implement their own internal diffing of these properties and make the minimal corresponding changes to the DOM manually.

I think it's a lot of overhead if someone just wants declarative pointer event binding to work. So, this is exactly what [&lt;Pointable/&gt;](https://www.npmjs.com/package/react-pointable) does [under the hood](https://github.com/MilllerTime/react-pointable/blob/master/src/index.jsx#L106). A user can bind pointer events exactly like other React events. The main difference is that instead of getting synthetic event objects from React, the handlers will receive events directly from the browser, or PEP.

I've written unit tests for the internal diffing code, and haven't experienced any issues in my real-world usage.

If you're open to linking to an external package for React support, I'm happy to write up a usage example for it, and stand behind the package.

**Comment by scottgonzalez** [comment]
> If you're open to linking to an external package for React support, I'm happy to write up a usage example for it, and stand behind the package.

Absolutely. Can you send a PR that adds a link with a short blurb? Just a sentence or two is fine, but feel free to write more.
