### ISSUE TITLE
pointercancel does not get triggered

### ISSUE THREAD

**Issue by Bortxx** [jquery/PEP#290]
Using "pointercancel" event to detect when user is dragging off the browsers viewport since "pointerup" is not triggered. "pointercancel" does not get raised. In fact I haven't found any behavior that raises it.

**Comment by scottgonzalez** [comment]
Are you referring to dragging a mouse off the viewport? PEP won't fire `pointercancel` for any mouse actions because there's no such concept in Mouse Events. For the most part you'll only get `pointercancel` if there's a native `touchcancel` event.

**Comment by patrickhlauke** [comment]
and for reference (though this may need updating, not sure how accurate it still is) `touchcancel` only triggers in specific situations https://alxgbsn.co.uk/2011/12/23/different-ways-to-trigger-touchcancel-in-mobile-browsers/

**Comment by Bortxx** [comment]
The documentation her states that it should: http://www.javascriptkit.com/javatutors/touchevents.shtml
According to this "touchend" states: "....such as if the user's finger slides out of the element first or even off the edge of the screen."
And for "touchcancel" it states: " 	Triggers when the touch point no longer registers on the touch surface. This can occur if the user has moved the touch point outside the browser UI....."
I know you guys use the native touch API under covers so shouldn't this work with pointer events?

I have an application where the user touches a spot and then drags up or down. While the touch is down some resources get allocated (timers, etc.) and I dispose of them on touchup. But when the user moves the touch off screen I would like to capture that and treat it as a touch up so I can release the resources. How can one capture touch drag off screen?

**Comment by patrickhlauke** [comment]
> The documentation here states that it should: http://www.javascriptkit.com/javatutors/touchevents.shtml
According to this "touchend" states: "....such as if the user's finger slides out of the element first or even off the edge of the screen."
And for "touchcancel" it states: " Triggers when the touch point no longer registers on the touch surface. This can occur if the user has moved the touch point outside the browser UI....."

It's not very authoritative documentation. And...well, they're wrong. Most browsers have bizarre quirks as to when they fire `touchcancel`, as documented in the link I gave. And yes, as PEP sits on top of touch events, this will result in the same bizarre quirks in when `pointercancel` gets fired.

Or are you suggesting that your code, when just using touch events instead of pointer events via PEP, works as expected / gets `touchcancel`?

**Comment by Bortxx** [comment]
No you are right I can't get the touchcancel to work even using touch events.

**Comment by scottgonzalez** [comment]
I'm going to close this since there's nothing we can do to improve the situation. We can only promote `touchcancel` to `pointercancel`, we can't detect scenarios where a cancelation should have occurred.

**Comment by vorg** [comment]
@scottgonzalez here is how to detect mouse release outside of the window

```javascript
// clic on the window, move your mouse outside of the browser bounds and release
window.addEventListener('mouseup', function (e) {
   console.log('mouse released')
})
```
