### ISSUE TITLE
IOS not reporting "pen"

### ISSUE THREAD

**Issue by niclaslindberg** [jquery/PEP#295]
Hi.

I've noticed that IPad pro (the only IOS device I've tested on with pen) does report pen gestures as "touch". I have read different comments on the forum about reporting everything as "touch" but what's the status?

Thanks!

**Comment by scottgonzalez** [comment]
PEP will never be able to report something as a pen because if PEP is in use, that means the browser is not exposing pointing devices other than mouse and touch.

In this specific case, iOS only has support for one type of pointing device: touch. There is no concept of anything else. As a result, PEP will see everything in iOS as a touch event and therefore can only conclude that the type is touch.

**Comment by patrickhlauke** [comment]
To add some further context: while native apps on iOS do have a way of recognising the Apple Pencil (including tilt etc, see https://developer.apple.com/library/ios/releasenotes/General/WhatsNewIniOS/Articles/iOS9_1.html#//apple_ref/doc/uid/TP40016572-DontLinkElementID_3), Safari does not offer any way to differentiate a touch from a Pencil/Stylus interaction or to access any of the tilt info). In Safari/WebViews a Pencil is exposed just like a regular touch.
