### ISSUE TITLE
Issues in "shadow" sample

### ISSUE THREAD

**Issue by jzaefferer** [jquery/PEP#305]
While testing the native PE implementation in Chrome, I noticed some issues in /samples/shadow/index.html

`host.webkitCreateShadowRoot()` doesn't exist anymore, changing that to `host.createShadowRoot()` works fine.

`PointerEventsPolyfill.register(s)` doesn't exist anymore, and I can't even tell when that was removed or what it did. I can tell though that there's a difference between the PEP and the native implementation, at least without this call (or whatever it did), the shadow element doesn't trigger pointerdown events.

**Comment by patrickhlauke** [comment]
@rbyers any pointers here?

**Comment by NavidZ** [comment]
We don't have any test covering the pointer events for shodaw DOM. We'll need to work on that. I put it in my queue.

**Comment by IanBellomy** [comment]
PEP pointer events are indeed not composed and so do not flow across the (v1) ShadowDOM. 

This means that a PEP PointerEvent dispatched on an element in a shadow will not trigger capture listeners in ancestors, including the document. 

This bit me while doing multi-touch via pointer events. Multi-touch requires caching pointer events by id and clearing them on pointerup. But because a shadow can be swallow these events, the caching (and multi-touch handling) can break.

**Comment by patrickhlauke** [comment]
**PEP has now [entered emeritus status at the OpenJS Foundation](https://openjsf.org/blog/2021/02/10/pointer-events-polyfill-pep-enters-emeritus-status-at-the-openjs-foundation/). This repository is now archived.**
