### ISSUE TITLE
CdnFallbackExpression for pep.js

### ISSUE THREAD

**Issue by arodriguezpreference** [jquery/PEP#330]
I am using the bundle feature of ASP.NET MVC to include PEP library in my project, referenced to CDN 'https://code.jquery.com/pep/0.4.1/pep.min.js'. I need a _CdnFallbackExpression_ to define the fallback (force my server copy of 'pep.min.js' usage) if the CDN fails. But I do not know what expression to use.
Can you tell me a JavaScript expression to check if library is loaded in the project?

**Comment by bethge** [comment]
Afraid I am not familiar with ASP.NET MVC bundling. To check if Pointer Events are supported PEP checks if `window.PointerEvent` is set. If it is not set, PEP sets `window.PointerEvent`. I would guess you only need to load PEP if `window.PointerEvent` is unset, since otherwise it is either natively supported or PEP already loaded.
Hope this helps.

**Comment by scottgonzalez** [comment]
Yup, the existence of `window.PointerEvent` won't explicitly tell you if PEP is loaded, but it will tell whether you need to load it. I'm going to close this since we've provided the expression. If you have more questions about this, feel free to continue commenting on this issue and we'll respond.

**Comment by arodriguezpreference** [comment]
Reviewing this topic and looking at the PEP library code, I found the _CdnFallbackExpression_ I need: `window.PointerEventsPolyfill`
