### ISSUE TITLE
Support iOS stylus

### ISSUE THREAD

**Issue by scottgonzalez** [jquery/PEP#342]
iOS added stylus support, exposing three new properties: `touchType`, `altitudeAngle`, and `azimuthAngle`. See https://github.com/w3c/touch-events/pull/81

**Comment by patrickhlauke** [comment]
randomly throwing out an observation: assuming iOS supports both a Pencil and regular finger touch simultaneously (sadly I don't have a device to test this), this will likely require a change in the `isPrimary` logic currently present in touch.js, which of course assumes that all touch events are of `pointerType == "touch"` and there can only be one primary.

assuming that iOS does not support more than one Pencil simultaneously (again, would need to test), it may be possible to short-circuit this by just making anything that has `touchType == "stylus"` a primary pen pointer, and excluding it from any logic that tries to determine the primary touch.

**Comment by raedle** [comment]
iOS only supports one Pencil (it allows only to pair 1 pencil). In Safari, the pen can be distinguished by checking the force property on the event object. No force mean touch and force != 0 means pen.

Hope that helps

**Comment by patrickhlauke** [comment]
parking this here for now: @rbyers pointed to the trigonometry used in chrome - this can likely be adapted to transmute `altitudeAngle`/`azimuthAngle` into `tiltX`/`tiltY`
https://cs.chromium.org/chromium/src/ui/events/blink/blink_event_util.cc?sq=package:chromium&dr=CSs&l=907
https://cs.chromium.org/chromium/src/content/browser/renderer_host/input/motion_event_web.cc?sq=package:chromium&dr=CSs&l=143

**Comment by mperktold** [comment]
Is there any update on this?

I would like to use pointer events with `tiltX` and `tiltY`, and precisely because of iOS, I need a polyfill for having pointer events at all.

I could create a pull request to calculate the tilt angles if you like.
However, I did not really understand how to create corresponding test cases in your setup.

**Comment by mperktold** [comment]
In the meantime, I investigated how to calculate `tiltX` and `tiltY`.

# Results
```
tiltX = atan(cos(azi) / tan(alt))
tiltY = atan(sin(azi) / tan(alt))
```
where `alt` denotes the altitude angle and `azi` denotes the azimuth angle.

Also, see the section on special cases

# Derivation

In case you wonder how to derive these formulae and you want to check whether they are correct,
here is my approach.

I looked into the links provided by @patrickhlauke, but I couldn't find any related calculations, probably because the code has changed since posting the links.

However, I found this wiki article to be useful: https://en.wikipedia.org/wiki/Spherical_coordinate_system.

It describes the spherical coordinate system, which apparently is very similar to [the one used by iOS](https://rawgit.com/RByers/touch-events/safari-stylus/index.html#touch-interface), except that instead of an _altitude angle_ from the screen to the pen, there is a _polar angle_ measured from the z-axis to the pen.

There is a section named "Coordinate system conversions", which provides the formalae for converting a vector in this system to the cartesian coordinate system, namely to _x_, _y_, and _z_ values. To replace the polar angle with the altitude angle, we only have to change `sin` to `cos `and vice versa, so we get:
```
x = r cos(alt) cos(azi)
y = r cos(alt) sin(azi)
z = r sin(alt)
```
where `r`denotes the radius, whereas `alt` and `azi` denote the altitude angle and the azimuth angle, respectively.

Now we want to come up with similar equations involving `tiltX` and `tiltY` instead of `alt` and `azi`.

To compute `x`, we first compute the length of the projection of the vector on the xz-plane, which is `r cos(tiltY)`. Then we only need to multiply that value with `sin(tiltX)` to get `x`.
The other coordinates are very similar and we get the following system of equations:

```
r sin(tiltX) cos(tiltY) = x = r cos(alt) cos(azi)
r cos(tiltX) sin(tiltY) = y = r cos(alt) sin(azi)
r cos(tiltX) cos(tiltY) = z = r sin(alt)
```

Now we use `x/z` to get `sin(tiltX)/cos(tiltX) = cos(alt) cos(azi) / sin(alt)`.
Since `sin x / cos x = tan x`, we have
```
tan(tiltX) = cos(azi) / tan(alt)
```
and therefore
```
tiltX = atan(cos(azi) / tan(alt))
```

Similarly, from `y/z` we get
```
tiltY = atan(sin(azi) / tan(alt))
```

# Special Cases
Now we need to consider some special cases for values of `alt` and `azi`.

If `alt = azi = 0`, then the device does not support the properties, and we should also set `tiltX = tiltY = 0`.

If `alt` is `PI/2`, then both `tiltX` and `tiltY` are 0.

If `alt` is 0, then `|tiltX| = |tiltY| = PI/2 - alt`.
To compute the signs, we look at `azi`:
- `tiltX` is positive iff `azi < PI/2` or `azi > 3 PI/2`
- `tiltY` is positive iff `azi < PI`

Note that in the last case, the information provided by `azi` is lost.
By the absolute values of the angles we know that the pen lies flat, and by the signs we also know in which quadrant the cap lies, but we don't know the actual direction.

However, it's probably safe to assume that the pen can only touch the screen if `azi > 0`. Thus, a value of 0 would always indicates that the device does not support the property, and we can drop the last case.

**Comment by mperktold** [comment]
I forgot to mention that both `azimuthAngle` and `altitudeAngle` return radiants, whereas `tiltX` and `tiltY` should be in degrees.

Therefore, the values calculated as explained above need to be multiplied by `100 / Math.PI` before setting them es properties of the resulting `PointerEvent`.

That being said, I implemented these transformations in custom touch handlers and indeed the resulting angles seem reasonable, so now I'm quite confident that the formulae are correct.

**Comment by marcello3d** [comment]
@mperktold any chance you can make a PR with your changes? otherwise I can take a stab at it
