### ISSUE TITLE
event.originalEvent.touches  No TouchList

### ISSUE THREAD

**Issue by rainjm** [jquery/PEP#348]
event.originalEvent.touches  No TouchList

I want to achieve double finger zoom function

**Comment by patrickhlauke** [comment]
There's no point adding the touchlists to the originalEvent, as real pointer events don't have those. so in browsers that have native pointer events support, you wouldn't get those anyway, meaning that any code you wrote that uses them won't work there...at that point, you might as well write touch event specific code rather than using PEP.

The way to handle multitouch scenarios with pointer events is to track each pointer yourself (see https://patrickhlauke.github.io/getting-touchy-presentation/#327 for instance)
