### ISSUE TITLE
Maintenance plans

### ISSUE THREAD

**Issue by darkowic** [jquery/PEP#379]
Hello everyone!

Is there any plan for maintaining this project? The polyfill is still needed on Safari devices (https://caniuse.com/#feat=pointer) and many people are using it.

The project seems to be abandon but there is no any official announcement about it.

Are there any other libraries providing the pointer-event polyfill?

**Comment by scottgonzalez** [comment]
See https://github.com/jquery/PEP/issues/355#issuecomment-422361631

**Comment by darkowic** [comment]
@drcmda you merged 2 mrs a few days ago but there is no changelog or so ever about it. Any news about the library?

**Comment by drcmda** [comment]
AFAIK the project is on hold. I merged the last bug-fixes that were left hanging for a year in order to at least make it work. I have no affiliation otherwise. But turns out it's still broken in IOS. From my own struggle with PE i think there are no alternatives. Rich Harris made one, but it can't capture. PE are now out in Safaris technical preview, which is glimmer of hope.

**Comment by Textras** [comment]
Actually looks like there is directionality, as it were, towards adoption https://webkit.org/blog/9281/release-notes-for-safari-technology-preview-85/
